server:
  port: 0
spring:
  cloud:
    stream:
      function:
        bindings:
          saveToDB-in-0: timeDemandExchange
  data:
    mongodb:
      username: rootuser
      password: rootpass
      database: iesodemand
      port: 27017
      host: localhost
      authentication-database: admin