version: "3.8"
services:
  ieso-pred-rabbitmq:
    image: rabbitmq:3-management
    container_name: ieso-pred-rabbitmq
    restart: always
    hostname: my-rabbit
    ports:
      - 15672:15672
      - 5672:5672
  ieso-pred-mongodb:
    image: mongo
    container_name: ieso-pred-mongodb
    command: ["mongod", "--replSet", "rs0", "--auth", "--bind_ip_all", "--keyFile", "/mongodb-keyfile"]
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./mongodb-keyfile:/mongodb-keyfile:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  ieso-pred-mongo-express:
    image: mongo-express
    container_name: ieso-pred-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: nimda
      ME_CONFIG_MONGODB_SERVER: ieso-pred-mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network