server:
  port: 0
spring:
  cloud:
    function:
      definition: saveToDB;saveWEathergyToDB;saveForecastToDB
    stream:
      bindings:
        saveToDB-in-0:
          destination: timeDemandExchange
        saveWEathergyToDB-in-0:
          destination: wEathergyDataExchange
        saveForecastToDB-in-0:
          destination: forecastData
  data:
    mongodb:
#      username: rootuser
#      password: rootpass
      database: iesodemand
      port: 27017
      host: localhost
      authentication-database: admin
      auto-index-creation: true