server:
  port: 0
spring:
  cloud:
    function:
      definition: parseXml;createMissingWEathergy;updateCurrHourWeather
    stream:
      bindings:
        parseXml-in-0:
          destination: xmlString
        parseXml-out-0:
          destination: timeDemandExchange
        createMissingWEathergy-in-0:
          destination: updateWEathergyInfo
        createMissingWEathergy-out-0:
          destination: wEathergyDataExchange
        updateCurrHourWeather-in-0:
          destination: updateCurrHourWeather
        updateCurrHourWeather-out-0:
          destination: forecastData
  data:
    mongodb:
#      username: rootuser
#      password: rootpass
      database: iesodemand
      port: 27017
      host: localhost
      authentication-database: admin
openWeather:
  apiKey: e427ead8cf57d148a6edf83a69d56fa9