spring:
  application:
    name: open-weather-map-historical-weather-getter
  data:
    mongodb:
      #      username: rootuser
      #      password: rootpass
      database: iesodemand
      port: 27017
      host: localhost
      authentication-database: admin
openweathermap:
  api-key: e427ead8cf57d148a6edf83a69d56fa9
  base-url: https://api.openweathermap.org/data/3.0/onecall
cities:
  Toronto:
    - 43.6534817
    - -79.3839347
  Markham:
    - 43.8563707
    - -79.3376825
