ieso:
  source:
    url: "https://www.ieso.ca/-/media/Files/IESO/uploaded/Chart/ontario_demand_multiday.xml"

server:
  port: 0

spring:
  cloud:
    stream:
      function:
        bindings:
          getXMLFromIESO-out-0: xmlString
      poller:
        fixed-delay: 60000